import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../data/weight_model.dart';
import '../data/weight_repository.dart';

final weightRepositoryProvider = Provider((ref) {
  return WeightRepository(Supabase.instance.client);
});

final weightDateProvider = NotifierProvider<WeightDateNotifier, DateTime>(
  WeightDateNotifier.new,
);

class WeightDateNotifier extends Notifier<DateTime> {
  @override
  DateTime build() => DateTime.now();

  void setDate(DateTime date) => state = date;
}

class WeightNotifier extends AsyncNotifier<List<WeightLog>> {
  @override
  Future<List<WeightLog>> build() async {
    final repo = ref.watch(weightRepositoryProvider);
    final date = ref.watch(weightDateProvider);
    return repo.getWeightLogs(date);
  }

  Future<void> addLog({
    required double weight,
    required DateTime date,
    double? skeletalMuscle,
    double? bodyFat,
    String? notes,
  }) async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return;

    final log = WeightLog(
      id: '', // Generated by Repo/DB
      userId: user.id,
      weight: weight,
      skeletalMuscle: skeletalMuscle,
      bodyFat: bodyFat,
      notes: notes,
      date: date,
      createdAt: DateTime.now(),
    );

    final repo = ref.read(weightRepositoryProvider);
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await repo.addWeightLog(log);
      // Invalidate latest log provider to refresh dashboard
      ref.invalidate(latestWeightLogProvider);
      return repo.getWeightLogs(date);
    });
  }
}

final weightProvider = AsyncNotifierProvider<WeightNotifier, List<WeightLog>>(
  () {
    return WeightNotifier();
  },
);

final latestWeightLogProvider = FutureProvider<WeightLog?>((ref) async {
  final repo = ref.watch(weightRepositoryProvider);
  return repo.getLatestWeightLog();
});

final recentWeightLogsProvider = FutureProvider<List<WeightLog>>((ref) async {
  final repo = ref.watch(weightRepositoryProvider);
  // Watch for changes to weightProvider to trigger refresh
  ref.watch(weightProvider);
  return repo.getRecentWeightLogs();
});
