import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../data/weight_model.dart';
import '../data/weight_repository.dart';

final weightRepositoryProvider = Provider((ref) {
  return WeightRepository(Supabase.instance.client);
});

class WeightNotifier extends AsyncNotifier<List<WeightLog>> {
  late WeightRepository _repo;
  DateTime _selectedDate = DateTime.now();

  @override
  Future<List<WeightLog>> build() async {
    _repo = ref.watch(weightRepositoryProvider);
    return _loadLogs();
  }

  Future<List<WeightLog>> _loadLogs() async {
    return _repo.getWeightLogs(_selectedDate);
  }

  Future<void> setDate(DateTime date) async {
    _selectedDate = date;
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() => _loadLogs());
  }

  DateTime get selectedDate => _selectedDate;

  Future<void> addLog({
    required double weight,
    required DateTime date,
    double? skeletalMuscle,
    double? bodyFat,
    String? notes,
  }) async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return;

    final log = WeightLog(
      id: '', // Generated by Repo/DB
      userId: user.id,
      weight: weight,
      skeletalMuscle: skeletalMuscle,
      bodyFat: bodyFat,
      notes: notes,
      date: date,
      createdAt: DateTime.now(),
    );

    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await _repo.addWeightLog(log);
      // Invalidate latest log provider to refresh dashboard
      ref.invalidate(latestWeightLogProvider);
      return _loadLogs();
    });
  }
}

final weightProvider =
    AsyncNotifierProvider<WeightNotifier, List<WeightLog>>(() {
      return WeightNotifier();
    });

final latestWeightLogProvider = FutureProvider<WeightLog?>((ref) async {
  final repo = ref.watch(weightRepositoryProvider);
  return repo.getLatestWeightLog();
});

final recentWeightLogsProvider = FutureProvider<List<WeightLog>>((ref) async {
  final repo = ref.watch(weightRepositoryProvider);
  // Watch for changes to weightProvider to trigger refresh
  ref.watch(weightProvider); 
  return repo.getRecentWeightLogs();
});